// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Agents qu'on sait lancer. En ajouter un : une variante ici, un `Driver` dans son fichier.
 */
export type AgentKind = "claude";
