// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorKind } from "./ErrorKind";

/**
 * Forme reçue par le front quand une commande échoue : `kind` choisit le texte traduit.
 */
export type AppError = { kind: ErrorKind, message: string, };
