// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttachmentKind } from "./AttachmentKind";

export type Attachment = { 
/**
 * Ce que l'agent reçoit : l'image elle-même, ou le chemin du fichier qu'il lira.
 */
path: string, name: string, kind: AttachmentKind, 
/**
 * Copie de l'image dans le dossier des pièces jointes, le seul que la webview peut afficher.
 */
preview: string | null, };
