// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Effort } from "./Effort";
import type { ModelInfo } from "./ModelInfo";

/**
 * Modèles proposés par l'agent installé, tels qu'il les décrit lui-même.
 */
export type Catalog = { models: Array<ModelInfo>, 
/**
 * `value` du modèle utilisé quand on n'en choisit aucun.
 */
defaultModel: string | null, defaultEffort: Effort, };
