// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentKind } from "./AgentKind";

/**
 * Ce que la barre latérale affiche d'un chat, sans charger sa conversation.
 */
export type ChatSummary = { id: string, projectId: string | null, number: number, agent: AgentKind, };
