// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnOptions } from "./TurnOptions";

export type ChatContent = { sessionId: string | null, options: TurnOptions, 
/**
 * Messages tels que le front les affiche : Rust les range sans les lire.
 */
items: unknown[], };
