// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Effort } from "./Effort";

export type ModelInfo = { value: string, label: string, description: string, 
/**
 * Vide quand le modèle ne règle pas son effort.
 */
efforts: Array<Effort>, };
