// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ce que le système laisse faire. `Unavailable` : rien à autoriser ici (sous `tauri dev` sur macOS).
 */
export type NotificationPermission = "granted" | "denied" | "undetermined" | "unavailable";
