// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Pas de mode « validation manuelle » : Nuée laisse l'agent agir seul.
 */
export type PermissionMode = "bypass" | "auto";
