// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentKind } from "./AgentKind";
import type { TurnOptions } from "./TurnOptions";

/**
 * Ce qui définit le process d'un chat. Le même process sert tous les tours tant que ça ne change pas.
 */
export type SessionSpec = { chatId: string, agent: AgentKind, 
/**
 * Dossier du projet. `None` : chat sans projet, l'agent travaille dans un dossier vide propre au chat.
 */
cwd: string | null, 
/**
 * Session renvoyée par l'agent : la reprendre garde le fil quand le process doit être relancé.
 */
sessionId: string | null, options: TurnOptions, };
