// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentKind } from "./AgentKind";
import type { TurnOptions } from "./TurnOptions";

export type TurnRequest = { chatId: string, agent: AgentKind, 
/**
 * Dossier du projet. `None` : chat sans projet, l'agent travaille dans un dossier vide propre au chat.
 */
cwd: string | null, prompt: string, 
/**
 * Session renvoyée par l'agent au tour précédent : la reprendre garde le fil de la conversation.
 */
sessionId: string | null, options: TurnOptions, };
