// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentKind } from "./AgentKind";

export type TurnRequest = { chatId: string, agent: AgentKind, cwd: string, prompt: string, 
/**
 * Session renvoyée par l'agent au tour précédent : la reprendre garde le fil de la conversation.
 */
sessionId: string | null, };
