// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Effort } from "./Effort";
import type { PermissionMode } from "./PermissionMode";

/**
 * Réglages d'un chat, repris à chaque tour : en changer en cours de conversation est possible.
 */
export type TurnOptions = { mode: PermissionMode, 
/**
 * Valeur prise dans le catalogue de l'agent ; `None` laisse l'agent choisir.
 */
model: string | null, effort: Effort | null, };
